import ProjectDescription

let workspace = Workspace(
    name: "NavExpo",
    projects: [
        "NavExpo",
        "Features/HomeFeature",
        "Features/ListFeature",
        "Features/ProfileFeature",
        "Shared"
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .enabled()
    )
)
